# Generated by Django 5.1.4 on 2025-02-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artists', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('valence', models.FloatField()),
                ('acousticness', models.FloatField()),
                ('danceability', models.FloatField()),
                ('duration_ms', models.FloatField()),
                ('energy', models.FloatField()),
                ('explicit', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('key', models.FloatField()),
                ('liveness', models.FloatField()),
                ('loudness', models.FloatField()),
                ('mode', models.FloatField()),
                ('popularity', models.FloatField()),
                ('speechiness', models.FloatField()),
                ('tempo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_songs', models.TextField()),
                ('recommended_songs', models.TextField()),
            ],
        ),
    ]
